# Generated by Django 4.1.3 on 2022-12-01 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSampcom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(max_length=50)),
                ('gst_no', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Single Bed', 'Single Bed'), ('Double Bed', 'Double Bed'), ('Luxury Room', 'Luxury Room')], default='Single Bed', max_length=50)),
                ('room_number', models.IntegerField()),
                ('room_price', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('hotel_id', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='HotelRooms', related_query_name='HotelRoom', to='AppSampcom.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='booking_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('hotel_booking_id', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bookingHotels', related_query_name='bookingHotel', to='AppSampcom.hotel')),
                ('room_id', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='RoomNumbers', related_query_name='RoomNumber', to='AppSampcom.room')),
                ('user_id', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='UserBooking', related_query_name='UserBookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
