# Generated by Django 4.1.3 on 2022-12-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSampcom', '0002_hotel_alter_user_updated_on_room_booking_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hotel_id',
            new_name='hotel_room_id',
        ),
    ]
